# Generated by Django 5.0.6 on 2026-10-04 14:20

import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Match title, e.g. 'Chelsea vs Arsenal' or 'UFC 300: Main Card'", max_length=250)),
                ('slug', models.SlugField(help_text='Unique URL slug (auto-generated from title)', max_length=250, unique=True)),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Match poster image (Recommended size: 450x300px)', keep_meta=True, null=True, quality=85, scale=None, size=[450, 300], upload_to='sports_thumbnails/')),
                ('description', models.TextField(blank=True, help_text='Match summary or description')),
                ('embed_code', models.TextField(blank=True, help_text='HTML / iframe embed code for the live stream (Only rendered for VIP subscribers)')),
                ('sport', models.CharField(choices=[('Football', 'Football / Soccer'), ('Basketball', 'Basketball'), ('Boxing', 'Boxing / MMA / UFC'), ('Tennis', 'Tennis'), ('Formula 1', 'Formula 1 / Racing'), ('Other', 'Other Sports')], default='Football', help_text='Category of sport', max_length=100)),
                ('team_home', models.CharField(blank=True, help_text='Home team/player name (optional)', max_length=100)),
                ('team_away', models.CharField(blank=True, help_text='Away team/player name (optional)', max_length=100)),
                ('match_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the match')),
                ('match_time', models.TimeField(blank=True, help_text='Kick-off / Start time (optional)', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Check to publish on the website')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to highlight on top of sports listings')),
                ('views', models.PositiveIntegerField(default=0, help_text='Total page views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sports Match',
                'verbose_name_plural': 'Sports Matches',
                'ordering': ['-match_date', '-created_at'],
            },
        ),
    ]
