# Generated by Django 4.2.13 on 2025-09-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_media_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_password_protected',
            field=models.BooleanField(default=False, help_text='Check if this post is password protected'),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, help_text='Optional password for protected posts', max_length=200, null=True),
        ),
    ]
