# Generated by Django 4.2.13 on 2026-07-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_via_email',
            field=models.BooleanField(default=False),
        ),
    ]
