# Generated by Django 5.0.6 on 2026-09-27 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. VIP Monthly, VIP Yearly', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='NGN', help_text='e.g. NGN, USD, EUR', max_length=10)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Duration of access in days (e.g. 30, 90, 365)')),
                ('description', models.TextField(blank=True, help_text='Brief summary of what this plan offers')),
                ('features', models.TextField(blank=True, help_text='Perks separated by line, e.g.:\n100% Ad-Free Browsing\nUltra-Fast Download Links\nExclusive VIP Badge\nPriority Customer Support')),
                ('badge_text', models.CharField(blank=True, help_text="Optional highlight badge like 'Most Popular' or 'Best Value'", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is visible to users')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which plans appear on the pricing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('payment_method', models.CharField(choices=[('simulated', 'Simulated / Test Checkout'), ('bank_transfer', 'Manual Bank Transfer'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe')], default='simulated', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('proof_of_payment', models.FileField(blank=True, help_text='Upload receipt/screenshot for manual transfer verification', null=True, upload_to='payment_proofs/')),
                ('user_notes', models.TextField(blank=True, help_text='Notes provided by user (e.g. sender name, bank, transfer details)', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes or reasons for approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
