# Generated by Django 5.0.6 on 2026-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Bank Name (e.g. OPay, Moniepoint, GTBank, Access Bank)', max_length=100)),
                ('account_number', models.CharField(help_text='Account Number for transfers', max_length=30)),
                ('account_name', models.CharField(help_text='Account Name matching the bank account', max_length=150)),
                ('instructions', models.TextField(blank=True, default='Make a direct bank transfer to the account details above. Enter your username or phone number in the transfer narration/remark. Then upload your transfer receipt below for fast verification.', help_text='Custom instructions displayed to the user on the checkout page')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is currently shown on the checkout page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Account Detail',
                'verbose_name_plural': 'Bank Account Details',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Manual Bank Transfer')], default='bank_transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='proof_of_payment',
            field=models.FileField(blank=True, help_text='Uploaded bank transfer receipt/screenshot', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('completed', 'Approved & Active'), ('failed', 'Declined / Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user_notes',
            field=models.TextField(blank=True, help_text='Notes provided by user (e.g. sender bank, account name, narration)', null=True),
        ),
    ]
